language: php

dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3

env:
  global:
    - CC_TEST_REPORTER_ID=72d58db2fba1e2cd7d118385aae8bb5b84cbf6b51fe263afc1c1ff47711ffd7a

before_script:
  - composer install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

addons:
  sonarcloud:
    organization: "grgk-github"

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml --log-junit build/logs/junit.xml --coverage-xml build/logs/coverage/xml --coverage-html build/logs/coverage/html
  - sonar-scanner

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
